[build]
  command = "npm run build"
  publish = "."

[dev]
  command = "npm run dev"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  NODE_VERSION = "18"
